### ISSUE TITLE
Project techstack setup

### ISSUE THREAD

**Issue by JohnTol322** [JohnTol322/MatchMyMovie#1]
For this project we will need:

- API (Spring Boot)
- Front-end application (React)
- Database (PostgreSQL -> docker)

**Comment by Bram1903** [comment]
Hey @JohnTol322! I’m curious about your choice to use MySQL for this project. Was there a specific reason behind it? I’ve noticed many larger companies leaning towards PostgreSQL recently since it's open-source, free, and often performs better with larger datasets. Just wondering if there were specific requirements or constraints that led you to go with MySQL! 😊
